import {
  type ApplicationRevision,
  type ContentSha256,
  createApplicationRevision,
  createContentSha256,
} from "@obsidian-ai-bridge/core";

/** Web Crypto algorithm required by protocol-stable content digests and fixed-length token comparison. */
const SHA_256_ALGORITHM = "SHA-256";

/**
 * Computes SHA-256 bytes with Web Crypto over the exact UTF-8 representation.
 *
 * @param value - Text whose UTF-8 bytes are hashed without normalization.
 * @returns The fixed-length digest bytes.
 */
export async function sha256Bytes(value: string): Promise<Uint8Array> {
  return new Uint8Array(
    await crypto.subtle.digest(
      SHA_256_ALGORITHM,
      new TextEncoder().encode(value),
    ),
  );
}

/**
 * Computes the canonical lowercase content digest required by M3 storage contracts.
 *
 * @param content - Exact note text to encode as UTF-8 and hash.
 * @returns A validated lowercase hexadecimal SHA-256 digest.
 */
export async function sha256Content(content: string): Promise<ContentSha256> {
  const digest = await sha256Bytes(content);
  const hexadecimal = Array.from(digest, (byte) =>
    byte.toString(16).padStart(2, "0"),
  ).join("");
  const contentSha256 = createContentSha256(hexadecimal);
  if (contentSha256 === undefined) {
    throw new Error("Web Crypto returned an invalid SHA-256 digest");
  }

  return contentSha256;
}

/**
 * Generates a fresh canonical UUID-v4 application generation identity.
 *
 * @returns A validated revision generated by the standards Web Crypto API.
 */
export function generateApplicationRevision(): ApplicationRevision {
  const revision = createApplicationRevision(crypto.randomUUID());
  if (revision === undefined) {
    throw new Error("Web Crypto returned an invalid UUID-v4 revision");
  }

  return revision;
}
